# Host list
# "name" is mandatory and will be used as target to connect
# "title" will be displayed as "human name" instead of "name" if specified
# All defaults values can be overriden per host basis
hosts:
  # Example / test root domain
  - name: calepin.de
    title: Calepin
      # Example / test url
  - name: xcl.freecluster.eu
    title: XCL Freecluster
  - name: sites.google.com/view/ateliermedia/
    title: Atelier Media
  # Example / test ip with port using ncat
  - name: "8.8.8.8"
    title: Google DNS
    port: 53
    use: ncat
  # Example / unavailable website
  - name: unavailable.website.com
    title: Unavailable website

# Site configuration
site:
  # Title
  title: Server Domain Status
  # Favicon / logo
  favicon: https://github.com/gigamaster/status/icon.png
  # Refresh rate of status images for client
  refresh_rate_sec: 1200

# Default values
defaults:
  # Default command to use
  # Supported values are :
  # - "curl"   [supports both uptime and response time, but only for HTTP/S requests]
  # - "ncat"   [supports both uptime and response time]
  # - "telnet" [supports only uptime]
  use: curl
  # Default timeout
  timeout: 30
  # Default port
  port: 443
  # Default number of ms before considering that host have latency problems
  status_slow_ms: 30000